### ISSUE TITLE
missing 'isOnline' keys

### ISSUE THREAD

**Issue by oaonder** [lmeulen/AsusRouterMonitor#2]
Hi,

First of all thanks for you code.
in line 257,  you assumed that 'isOnline' is available. But in somecases it's missing.
if (len(c) == 17) and (clnts['get_clientlist'][c]['isOnline'] == '1'):

So, it is better to check if the key is present. then go for filtering:
if (len(c) == 17) and "isOnline" in clnts['get_clientlist'][c]:

BTW, I am no coder. just a hobbiest. There may be a better way to handle missing 'isOnline' key.

I will use your code to create a telegram bot and send a message if a new client is associated in network.

Thanks.

**Comment by Barryq93** [comment]
line 273 also - put @oaonder line in both and worked perfectly for me

**Comment by lmeulen** [comment]
Added the check mentioned. Thanx for the feedback
